# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('house', models.CharField(max_length=20)),
                ('grade', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senders.sender'),
        ),
    ]
